# 17. Reading Files in Python
* __To read a text file in Python, you follow these steps:__
* __First, open a text file for reading by using the open() function.__
* __Second, read text from the text file using read(), readline(),readlines() method of the file object.__
* __Third, close the file using the file close() method, which frees up resources and ensures consistency across different Python versions.__
* __Method -----------------------------||Descriptions||__
* __Writable(): Returns whether the file can be written or not.__
* __Readable(): Returns whether the file stream can be read or not.__
* __Read(): Returns the file content.__
* __Readline(): Returns one line from the file.__
* __Readlines(): Returns a list of strings from the file.__
* __Write(): Writes the specified string to the file.__
* __Writelines(): Writes a list of strings to the file.__
* __close(): close the file.__
* __flush(): flushed the internal buffer.__
* __seek(): change the file position.__
* __tell(): Returns the current file.__
* __truncate(): Resize the file specified.__

In [1]:
filename="C:\\Users\\sanam\\OneDrive\\Documents\\sample.txt"
print(filename)
newVar=open(filename)
content=newVar.read()
content

C:\Users\sanam\OneDrive\Documents\sample.txt

"Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks. These cyberattacks are usually aimed at accessing, changing, or destroying sensitive information; extorting money from users through ransomware; or interrupting normal business processes.\n\nImplementing effective cybersecurity measures is particularly challenging today because there are more devices than people, and attackers are becoming more innovative.\n\nA successful cybersecurity posture has multiple layers of protection spread across the computers, networks, programs, or data that one intends to keep safe. In an organization, a unified threat management gateway system can automate integrations across products and accelerate key security operations functions: detection, investigation, and remediation. People, processes, and technology must all complement one another to create an effective defense from cyberattacks.\n\nTake our free Introduction to Cybersecurity course\n\nPeople\nUsers must understand and comply with basic data protection and privacy security principles like choosing strong passwords, being wary of attachments in email, and backing up data. Learn more about basic cybersecurity principles from these Top 10 Cyber Tips (PDF).\n\nProcesses\nOrganizations must have a framework for how they deal with both attempted and successful cyberattacks. One well-respected model, the NIST cybersecurity framework, can guide you. It explains how you can identify attacks, protect systems, detect and respond to threats, and recover from successful attacks.\n\nTechnology\nTechnology is essential to giving organizations and individuals the computer security tools needed to protect themselves from cyberattacks. Three main entities must be protected: endpoint devices like computers, smart devices, and routers; networks; and the cloud. Common technology used to protect these entities include next-generation firewalls, Domain Name System (DNS) filtering, malware protection, antivirus software, and email security solutions.\n\nWhy is cybersecurity important?\nIn today's connected world, everyone benefits from advanced cybersecurity solutions. At an individual level, a cybersecurity attack can result in everything from identity theft to extortion attempts, to the loss of important data like family photos. Everyone relies on critical infrastructure like power plants, hospitals, and financial service companies. Securing these and other organizations is essential to keeping our society functioning.\n\nEveryone also benefits from the work of cyberthreat researchers, like the team of 250 threat researchers at Talos, who investigate new and emerging threats and cyberattack strategies. They reveal new vulnerabilities, educate the public on the importance of cybersecurity, and strengthen open-source tools. Their work makes the internet safer for everyone.\n\n"

In [2]:
print(content)

Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks. These cyberattacks are usually aimed at accessing, changing, or destroying sensitive information; extorting money from users through ransomware; or interrupting normal business processes.

Implementing effective cybersecurity measures is particularly challenging today because there are more devices than people, and attackers are becoming more innovative.

A successful cybersecurity posture has multiple layers of protection spread across the computers, networks, programs, or data that one intends to keep safe. In an organization, a unified threat management gateway system can automate integrations across products and accelerate key security operations functions: detection, investigation, and remediation. People, processes, and technology must all complement one another to create an effective defense from cyberattacks.

Take our free Introduction to Cybersecurity course

People
Users must understand and comply with basic data protection and privacy security principles like choosing strong passwords, being wary of attachments in email, and backing up data. Learn more about basic cybersecurity principles from these Top 10 Cyber Tips (PDF).

Processes
Organizations must have a framework for how they deal with both attempted and successful cyberattacks. One well-respected model, the NIST cybersecurity framework, can guide you. It explains how you can identify attacks, protect systems, detect and respond to threats, and recover from successful attacks.

Technology
Technology is essential to giving organizations and individuals the computer security tools needed to protect themselves from cyberattacks. Three main entities must be protected: endpoint devices like computers, smart devices, and routers; networks; and the cloud. Common technology used to protect these entities include next-generation firewalls, Domain Name System (DNS) filtering, malware protection, antivirus software, and email security solutions.

Why is cybersecurity important?
In today's connected world, everyone benefits from advanced cybersecurity solutions. At an individual level, a cybersecurity attack can result in everything from identity theft to extortion attempts, to the loss of important data like family photos. Everyone relies on critical infrastructure like power plants, hospitals, and financial service companies. Securing these and other organizations is essential to keeping our society functioning.

Everyone also benefits from the work of cyberthreat researchers, like the team of 250 threat researchers at Talos, who investigate new and emerging threats and cyberattack strategies. They reveal new vulnerabilities, educate the public on the importance of cybersecurity, and strengthen open-source tools. Their work makes the internet safer for everyone.

In [3]:
#printing path of the file
print(newVar.name)

C:\Users\sanam\OneDrive\Documents\sample.txt

In [4]:
print(type(content))

<class 'str'>

In [5]:
newVar.closed

False

In [6]:
newVar.close()

In [7]:
newVar.closed

True

In [8]:
content

"Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks. These cyberattacks are usually aimed at accessing, changing, or destroying sensitive information; extorting money from users through ransomware; or interrupting normal business processes.\n\nImplementing effective cybersecurity measures is particularly challenging today because there are more devices than people, and attackers are becoming more innovative.\n\nA successful cybersecurity posture has multiple layers of protection spread across the computers, networks, programs, or data that one intends to keep safe. In an organization, a unified threat management gateway system can automate integrations across products and accelerate key security operations functions: detection, investigation, and remediation. People, processes, and technology must all complement one another to create an effective defense from cyberattacks.\n\nTake our free Introduction to Cybersecurity course\n\nPeople\nUsers must understand and comply with basic data protection and privacy security principles like choosing strong passwords, being wary of attachments in email, and backing up data. Learn more about basic cybersecurity principles from these Top 10 Cyber Tips (PDF).\n\nProcesses\nOrganizations must have a framework for how they deal with both attempted and successful cyberattacks. One well-respected model, the NIST cybersecurity framework, can guide you. It explains how you can identify attacks, protect systems, detect and respond to threats, and recover from successful attacks.\n\nTechnology\nTechnology is essential to giving organizations and individuals the computer security tools needed to protect themselves from cyberattacks. Three main entities must be protected: endpoint devices like computers, smart devices, and routers; networks; and the cloud. Common technology used to protect these entities include next-generation firewalls, Domain Name System (DNS) filtering, malware protection, antivirus software, and email security solutions.\n\nWhy is cybersecurity important?\nIn today's connected world, everyone benefits from advanced cybersecurity solutions. At an individual level, a cybersecurity attack can result in everything from identity theft to extortion attempts, to the loss of important data like family photos. Everyone relies on critical infrastructure like power plants, hospitals, and financial service companies. Securing these and other organizations is essential to keeping our society functioning.\n\nEveryone also benefits from the work of cyberthreat researchers, like the team of 250 threat researchers at Talos, who investigate new and emerging threats and cyberattack strategies. They reveal new vulnerabilities, educate the public on the importance of cybersecurity, and strengthen open-source tools. Their work makes the internet safer for everyone.\n\n"

In [9]:
filename="C:\Users\sanam\OneDrive\Documents\sample.txt"
print(filename)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (358823189.py, line 1)

In [ ]:
filename="C:\\Users\\sanam\\OneDrive\\Documents\\sample.txt"
print(filename)

In [ ]:
filename="C:\\Users\\sanam\\OneDrive\\Documents\\sample.txt"
print(filename)
newVar=open(filename)
content=newVar.read()
content

In [10]:
# How to open the file using second method
filename="C:\\Users\\sanam\\OneDrive\\Documents\\sample.txt"
with open(filename,'r') as f:
    print(f.read())

Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks. These cyberattacks are usually aimed at accessing, changing, or destroying sensitive information; extorting money from users through ransomware; or interrupting normal business processes.

Implementing effective cybersecurity measures is particularly challenging today because there are more devices than people, and attackers are becoming more innovative.

A successful cybersecurity posture has multiple layers of protection spread across the computers, networks, programs, or data that one intends to keep safe. In an organization, a unified threat management gateway system can automate integrations across products and accelerate key security operations functions: detection, investigation, and remediation. People, processes, and technology must all complement one another to create an effective defense from cyberattacks.

Take our free Introduction to Cybersecurity course

People
Users must understand and comply with basic data protection and privacy security principles like choosing strong passwords, being wary of attachments in email, and backing up data. Learn more about basic cybersecurity principles from these Top 10 Cyber Tips (PDF).

Processes
Organizations must have a framework for how they deal with both attempted and successful cyberattacks. One well-respected model, the NIST cybersecurity framework, can guide you. It explains how you can identify attacks, protect systems, detect and respond to threats, and recover from successful attacks.

Technology
Technology is essential to giving organizations and individuals the computer security tools needed to protect themselves from cyberattacks. Three main entities must be protected: endpoint devices like computers, smart devices, and routers; networks; and the cloud. Common technology used to protect these entities include next-generation firewalls, Domain Name System (DNS) filtering, malware protection, antivirus software, and email security solutions.

Why is cybersecurity important?
In today's connected world, everyone benefits from advanced cybersecurity solutions. At an individual level, a cybersecurity attack can result in everything from identity theft to extortion attempts, to the loss of important data like family photos. Everyone relies on critical infrastructure like power plants, hospitals, and financial service companies. Securing these and other organizations is essential to keeping our society functioning.

Everyone also benefits from the work of cyberthreat researchers, like the team of 250 threat researchers at Talos, who investigate new and emerging threats and cyberattack strategies. They reveal new vulnerabilities, educate the public on the importance of cybersecurity, and strengthen open-source tools. Their work makes the internet safer for everyone.

In [12]:
filename1="C:\\Users\\sanam\\OneDrive\\Documents\\sample.txt"
with open(filename1,'r') as f:
    print(f.read(10))
    print(f.read(20))
    print(f.read(30))
    print(f.read(40))
    print(f.read(100))

Cybersecur
ity is the practice
of protecting systems, network
s, and programs from digital attacks. Th
ese cyberattacks are usually aimed at accessing, changing, or destroying sensitive information; exto

In [13]:
filename2="C:\\Users\\sanam\\OneDrive\\Documents\\sample.txt"
with open(filename2,'r') as f:
    print(f.readline())
    print(f.readline())
    print(f.readline())
    print(f.readline())

Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks. These cyberattacks are usually aimed at accessing, changing, or destroying sensitive information; extorting money from users through ransomware; or interrupting normal business processes.



Implementing effective cybersecurity measures is particularly challenging today because there are more devices than people, and attackers are becoming more innovative.

In [14]:
filename3="C:\\Users\\sanam\\OneDrive\\Documents\\sample.txt"
with open(filename3,'r') as f:
    print(f.readlines(),type(f.readlines()))

['Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks. These cyberattacks are usually aimed at accessing, changing, or destroying sensitive information; extorting money from users through ransomware; or interrupting normal business processes.\n', '\n', 'Implementing effective cybersecurity measures is particularly challenging today because there are more devices than people, and attackers are becoming more innovative.\n', '\n', 'A successful cybersecurity posture has multiple layers of protection spread across the computers, networks, programs, or data that one intends to keep safe. In an organization, a unified threat management gateway system can automate integrations across products and accelerate key security operations functions: detection, investigation, and remediation. People, processes, and technology must all complement one another to create an effective defense from cyberattacks.\n', '\n', 'Take our free Introduction to Cybersecurity course\n', '\n', 'People\n', 'Users must understand and comply with basic data protection and privacy security principles like choosing strong passwords, being wary of attachments in email, and backing up data. Learn more about basic cybersecurity principles from these Top 10 Cyber Tips (PDF).\n', '\n', 'Processes\n', 'Organizations must have a framework for how they deal with both attempted and successful cyberattacks. One well-respected model, the NIST cybersecurity framework, can guide you. It explains how you can identify attacks, protect systems, detect and respond to threats, and recover from successful attacks.\n', '\n', 'Technology\n', 'Technology is essential to giving organizations and individuals the computer security tools needed to protect themselves from cyberattacks. Three main entities must be protected: endpoint devices like computers, smart devices, and routers; networks; and the cloud. Common technology used to protect these entities include next-generation firewalls, Domain Name System (DNS) filtering, malware protection, antivirus software, and email security solutions.\n', '\n', 'Why is cybersecurity important?\n', "In today's connected world, everyone benefits from advanced cybersecurity solutions. At an individual level, a cybersecurity attack can result in everything from identity theft to extortion attempts, to the loss of important data like family photos. Everyone relies on critical infrastructure like power plants, hospitals, and financial service companies. Securing these and other organizations is essential to keeping our society functioning.\n", '\n', 'Everyone also benefits from the work of cyberthreat researchers, like the team of 250 threat researchers at Talos, who investigate new and emerging threats and cyberattack strategies. They reveal new vulnerabilities, educate the public on the importance of cybersecurity, and strengthen open-source tools. Their work makes the internet safer for everyone.\n', '\n'] <class 'list'>

In [15]:
#paragraph()
with open(filename3,'r') as f:
    linenumber=1
    for i in f:
        print("line number:",linenumber,i)
        linenumber+=1

line number: 1 Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks. These cyberattacks are usually aimed at accessing, changing, or destroying sensitive information; extorting money from users through ransomware; or interrupting normal business processes.

line number: 2

line number: 3 Implementing effective cybersecurity measures is particularly challenging today because there are more devices than people, and attackers are becoming more innovative.

line number: 4

line number: 5 A successful cybersecurity posture has multiple layers of protection spread across the computers, networks, programs, or data that one intends to keep safe. In an organization, a unified threat management gateway system can automate integrations across products and accelerate key security operations functions: detection, investigation, and remediation. People, processes, and technology must all complement one another to create an effective defense from cyberattacks.

line number: 6

line number: 7 Take our free Introduction to Cybersecurity course

line number: 8

line number: 9 People

line number: 10 Users must understand and comply with basic data protection and privacy security principles like choosing strong passwords, being wary of attachments in email, and backing up data. Learn more about basic cybersecurity principles from these Top 10 Cyber Tips (PDF).

line number: 11

line number: 12 Processes

line number: 13 Organizations must have a framework for how they deal with both attempted and successful cyberattacks. One well-respected model, the NIST cybersecurity framework, can guide you. It explains how you can identify attacks, protect systems, detect and respond to threats, and recover from successful attacks.

line number: 14

line number: 15 Technology

line number: 16 Technology is essential to giving organizations and individuals the computer security tools needed to protect themselves from cyberattacks. Three main entities must be protected: endpoint devices like computers, smart devices, and routers; networks; and the cloud. Common technology used to protect these entities include next-generation firewalls, Domain Name System (DNS) filtering, malware protection, antivirus software, and email security solutions.

line number: 17

line number: 18 Why is cybersecurity important?

line number: 19 In today's connected world, everyone benefits from advanced cybersecurity solutions. At an individual level, a cybersecurity attack can result in everything from identity theft to extortion attempts, to the loss of important data like family photos. Everyone relies on critical infrastructure like power plants, hospitals, and financial service companies. Securing these and other organizations is essential to keeping our society functioning.

line number: 20

line number: 21 Everyone also benefits from the work of cyberthreat researchers, like the team of 250 threat researchers at Talos, who investigate new and emerging threats and cyberattack strategies. They reveal new vulnerabilities, educate the public on the importance of cybersecurity, and strengthen open-source tools. Their work makes the internet safer for everyone.

line number: 22

In [16]:
filename='C:\\Users\\sanam\\OneDrive\\Documents\\sample.txt'
print(filename)
with open(filename,'r') as f:
    data=f.read()
    count=0
    for i in data:
        count+=1
        #print(i)
    print("Character with space:",count)
    print("Character without space:",len(data.replace(' ',"")))

C:\Users\sanam\OneDrive\Documents\sample.txt
Character with space: 2870
Character without space: 2494

In [17]:
file="C:\\Users\\sanam\\OneDrive\\Documents\\sample.txt"
with open(file,'r') as s:
    par=1
    for i in s:
        print(par,i)
        par+=1

1 Cybersecurity is the practice of protecting systems, networks, and programs from digital attacks. These cyberattacks are usually aimed at accessing, changing, or destroying sensitive information; extorting money from users through ransomware; or interrupting normal business processes.

2

3 Implementing effective cybersecurity measures is particularly challenging today because there are more devices than people, and attackers are becoming more innovative.

4

5 A successful cybersecurity posture has multiple layers of protection spread across the computers, networks, programs, or data that one intends to keep safe. In an organization, a unified threat management gateway system can automate integrations across products and accelerate key security operations functions: detection, investigation, and remediation. People, processes, and technology must all complement one another to create an effective defense from cyberattacks.

6

7 Take our free Introduction to Cybersecurity course

8

9 People

10 Users must understand and comply with basic data protection and privacy security principles like choosing strong passwords, being wary of attachments in email, and backing up data. Learn more about basic cybersecurity principles from these Top 10 Cyber Tips (PDF).

11

12 Processes

13 Organizations must have a framework for how they deal with both attempted and successful cyberattacks. One well-respected model, the NIST cybersecurity framework, can guide you. It explains how you can identify attacks, protect systems, detect and respond to threats, and recover from successful attacks.

14

15 Technology

16 Technology is essential to giving organizations and individuals the computer security tools needed to protect themselves from cyberattacks. Three main entities must be protected: endpoint devices like computers, smart devices, and routers; networks; and the cloud. Common technology used to protect these entities include next-generation firewalls, Domain Name System (DNS) filtering, malware protection, antivirus software, and email security solutions.

17

18 Why is cybersecurity important?

19 In today's connected world, everyone benefits from advanced cybersecurity solutions. At an individual level, a cybersecurity attack can result in everything from identity theft to extortion attempts, to the loss of important data like family photos. Everyone relies on critical infrastructure like power plants, hospitals, and financial service companies. Securing these and other organizations is essential to keeping our society functioning.

20

21 Everyone also benefits from the work of cyberthreat researchers, like the team of 250 threat researchers at Talos, who investigate new and emerging threats and cyberattack strategies. They reveal new vulnerabilities, educate the public on the importance of cybersecurity, and strengthen open-source tools. Their work makes the internet safer for everyone.

22

In [18]:
fileName="C:\\Users\\sanam\\OneDrive\\Desktop\\twinkle.txt" #filenotfounderror:in file explorer, the file extension is not on that's why its getting error.
#print(file)
with open(fileName,'r') as f:
    print(f.read())

Twinkle, twinkle, little star,
How I wonder what you are!
Up above the world so high,
Like a diamond in the sky.

When the blazing sun is gone,
When he nothing shines upon,
Then you show your little light,
Twinkle, twinkle, all the night.

Then the trav'ller in the dark,
Thanks you for your tiny spark,
He could not see which way to go,
If you did not twinkle so.

In the dark blue sky you keep,
And often thro' my curtains peep,
For you never shut your eye,
Till the sun is in the sky.

'Tis your bright and tiny spark,
Lights the trav'ller in the dark:
Tho' I know not what you are,
Twinkle, twinkle, little star.

In [19]:
x="C:\\Users\\sanam\\OneDrive\\Desktop\\twinkle.txt"
vowChar=open(x)
content=vowChar.read()
content

"Twinkle, twinkle, little star,\nHow I wonder what you are!\nUp above the world so high,\nLike a diamond in the sky.\n\nWhen the blazing sun is gone,\nWhen he nothing shines upon,\nThen you show your little light,\nTwinkle, twinkle, all the night.\n\nThen the trav'ller in the dark,\nThanks you for your tiny spark,\nHe could not see which way to go,\nIf you did not twinkle so.\n\nIn the dark blue sky you keep,\nAnd often thro' my curtains peep,\nFor you never shut your eye,\nTill the sun is in the sky.\n\n'Tis your bright and tiny spark,\nLights the trav'ller in the dark:\nTho' I know not what you are,\nTwinkle, twinkle, little star."

In [20]:
x="C:\\Users\\sanam\\OneDrive\\Desktop\\twinkle.txt"
with open(x,'r') as f:
    print(f.read())

Twinkle, twinkle, little star,
How I wonder what you are!
Up above the world so high,
Like a diamond in the sky.

When the blazing sun is gone,
When he nothing shines upon,
Then you show your little light,
Twinkle, twinkle, all the night.

Then the trav'ller in the dark,
Thanks you for your tiny spark,
He could not see which way to go,
If you did not twinkle so.

In the dark blue sky you keep,
And often thro' my curtains peep,
For you never shut your eye,
Till the sun is in the sky.

'Tis your bright and tiny spark,
Lights the trav'ller in the dark:
Tho' I know not what you are,
Twinkle, twinkle, little star.

In [21]:
print(type(content))

<class 'str'>

In [22]:
print(content)

Twinkle, twinkle, little star,
How I wonder what you are!
Up above the world so high,
Like a diamond in the sky.

When the blazing sun is gone,
When he nothing shines upon,
Then you show your little light,
Twinkle, twinkle, all the night.

Then the trav'ller in the dark,
Thanks you for your tiny spark,
He could not see which way to go,
If you did not twinkle so.

In the dark blue sky you keep,
And often thro' my curtains peep,
For you never shut your eye,
Till the sun is in the sky.

'Tis your bright and tiny spark,
Lights the trav'ller in the dark:
Tho' I know not what you are,
Twinkle, twinkle, little star.

In [23]:
x="C:\\Users\\sanam\\OneDrive\\Desktop\\twinkle.txt"
with open(x,'r') as f:
    data=f.read()
    count=0
    for i in data.replace(' ',''):
        count+=1
        #print(count)
    print("character without space:",count)

character without space: 517

In [24]:
x="C:\\Users\\sanam\\OneDrive\\Desktop\\twinkle.txt"
with open(x,'r') as f:
    data=f.read()
    count=0
    for i in data:
        count+=1
    print("character with space:",count)  
    print("character without space:",len(data.replace(' ','')))

character with space: 616
character without space: 517

In [25]:
x="C:\\Users\\sanam\\OneDrive\\Desktop\\twinkle.txt"
with open(x,'r') as f:
    data=f.read()
    data1=data.split()
    wordCount=0
    for i in data1:
        if i == "Twinkle," or i == "twinkle," or i == "twinkle":
            wordCount+=1
            print(i)
    print(wordCount)

Twinkle,
twinkle,
Twinkle,
twinkle,
twinkle
Twinkle,
twinkle,
7

In [26]:
x="C:\\Users\\sanam\\OneDrive\\Desktop\\twinkle.txt"
with open(x,'r') as f:
    lineNumber=0
    for i in f:
        lineNumber+=1
        print("line number:",lineNumber,i)
    print(lineNumber)

line number: 1 Twinkle, twinkle, little star,

line number: 2 How I wonder what you are!

line number: 3 Up above the world so high,

line number: 4 Like a diamond in the sky.

line number: 5

line number: 6 When the blazing sun is gone,

line number: 7 When he nothing shines upon,

line number: 8 Then you show your little light,

line number: 9 Twinkle, twinkle, all the night.

line number: 10

line number: 11 Then the trav'ller in the dark,

line number: 12 Thanks you for your tiny spark,

line number: 13 He could not see which way to go,

line number: 14 If you did not twinkle so.

line number: 15

line number: 16 In the dark blue sky you keep,

line number: 17 And often thro' my curtains peep,

line number: 18 For you never shut your eye,

line number: 19 Till the sun is in the sky.

line number: 20

line number: 21 'Tis your bright and tiny spark,

line number: 22 Lights the trav'ller in the dark:

line number: 23 Tho' I know not what you are,

line number: 24 Twinkle, twinkle, little star.
24

In [6]:
x="C:\\Users\\sanam\\OneDrive\\Desktop\\twinkle.txt"
with open(x,'r') as f:
    data=f.read()
    words=data.split()
    wordList=[]
    count=0

    for i in range(len(words)):
        word=''
        for j in range(len(words[i])):
            word+=words[i][j]
        wordList.append(word)  
        count+=1
    print("List of words is:",wordList)   
    print("Total words is:",count)

List of words is: ['Twinkle,', 'twinkle,', 'little', 'star,', 'How', 'I', 'wonder', 'what', 'you', 'are!', 'Up', 'above', 'the', 'world', 'so', 'high,', 'Like', 'a', 'diamond', 'in', 'the', 'sky.', 'When', 'the', 'blazing', 'sun', 'is', 'gone,', 'When', 'he', 'nothing', 'shines', 'upon,', 'Then', 'you', 'show', 'your', 'little', 'light,', 'Twinkle,', 'twinkle,', 'all', 'the', 'night.', 'Then', 'the', "trav'ller", 'in', 'the', 'dark,', 'Thanks', 'you', 'for', 'your', 'tiny', 'spark,', 'He', 'could', 'not', 'see', 'which', 'way', 'to', 'go,', 'If', 'you', 'did', 'not', 'twinkle', 'so.', 'In', 'the', 'dark', 'blue', 'sky', 'you', 'keep,', 'And', 'often', "thro'", 'my', 'curtains', 'peep,', 'For', 'you', 'never', 'shut', 'your', 'eye,', 'Till', 'the', 'sun', 'is', 'in', 'the', 'sky.', "'Tis", 'your', 'bright', 'and', 'tiny', 'spark,', 'Lights', 'the', "trav'ller", 'in', 'the', 'dark:', "Tho'", 'I', 'know', 'not', 'what', 'you', 'are,', 'Twinkle,', 'twinkle,', 'little', 'star.']
Total words is: 119

In [7]:
with open(x,'r') as f:
    data=f.read()
    words=data.split()
    sumWord=[]
    for i in range(len(words)):
        length=0
        for j in range(len(words[i])):
            length+=1
        sumWord.append(length) 
    print(sumWord)  
    print(sum(sumWord))

[8, 8, 6, 5, 3, 1, 6, 4, 3, 4, 2, 5, 3, 5, 2, 5, 4, 1, 7, 2, 3, 4, 4, 3, 7, 3, 2, 5, 4, 2, 7, 6, 5, 4, 3, 4, 4, 6, 6, 8, 8, 3, 3, 6, 4, 3, 9, 2, 3, 5, 6, 3, 3, 4, 4, 6, 2, 5, 3, 3, 5, 3, 2, 3, 2, 3, 3, 3, 7, 3, 2, 3, 4, 4, 3, 3, 5, 3, 5, 5, 2, 8, 5, 3, 3, 5, 4, 4, 4, 4, 3, 3, 2, 2, 3, 4, 4, 4, 6, 3, 4, 6, 6, 3, 9, 2, 3, 5, 4, 1, 4, 3, 4, 3, 4, 8, 8, 6, 5]
494

In [ ]:
with open(x,'r') as f:
    data=f.read()
    word=data.split()
    wordLength=[]
    for i in range(len(word)):
        length=0
        for j in range(len(word[i])):
            length+=1
        wordLength.append(length)   
    print("length of word:",wordLength)  
    print("sum of word length:",sum(wordLength))

In [ ]:
import PyPDF2

In [ ]:
from PyPDF2 import PdfReader
filename="C:\\Users\\sanam\\OneDrive\\Desktop\\The-Happy-Prince-by-Oscar-Wilde.pdf"
print(filename)

In [1]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (4.13.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4) (4.14.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install lxml

Collecting lxml
  Downloading lxml-6.0.0-cp313-cp313-win_amd64.whl.metadata (6.8 kB)
Downloading lxml-6.0.0-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.0 MB 1.8 MB/s eta 0:00:02
   ------------- -------------------------- 1.3/4.0 MB 2.0 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.0 MB 2.1 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------- ----------- 2.9/4.0 MB 2.1 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 2.2 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 2.2 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 1.6 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install PyPDF2

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Note: you may need to restart the kernel to use updated packages.

In [4]:
!which python

'which' is not recognized as an internal or external command,
operable program or batch file.

In [5]:
!echo Hello from shell
!whoami

Hello from shell
sanapc\sana

In [8]:
import sys 
print(sys.executable)

C:\Users\sanam\AppData\Local\Programs\Python\Python313\python.exe

In [9]:
!dir 
!echo hello

 Volume in drive D has no label.
 Volume Serial Number is BE26-2C3F

 Directory of D:\python 2019

20-07-2025  14:43    <DIR>          .
17-07-2025  11:12    <DIR>          .ipynb_checkpoints
30-06-2025  14:27            21,201 10.exception handling.ipynb
14-07-2025  09:42            50,036 13.class and object.ipynb
07-07-2025  22:11            14,083 13.inheritance.ipynb
10-07-2025  12:01            13,852 14.ATM Project.ipynb
14-07-2025  09:41            48,951 15.Lambda Function in python.ipynb
15-07-2025  12:02            43,556 16.list comprehension.ipynb
20-07-2025  14:42            50,726 17.file handling.ipynb
20-07-2025  14:43             2,768 18.Writing files using python.ipynb
13-07-2025  14:57            34,613 2.string.ipynb
30-06-2025  04:44            36,655 3.list.ipynb
09-06-2025  13:39            23,450 4.tuples.ipynb
09-06-2025  13:53            12,652 5.sets.ipynb
09-06-2025  14:48            21,350 6.dictionary.ipynb
16-06-2025  22:59            35,345 7.conditions in python.ipynb
29-06-2025  12:52            48,321 8.Loop.ipynb
29-06-2025  13:12            32,394 9.functions in python.ipynb
06-07-2025  07:20            45,838 homework2.ipynb
08-07-2025  22:08            32,839 homework3.ipynb
14-07-2025  10:23             9,350 introduction.txt
13-07-2025  12:24            28,571 python basic.ipynb
09-07-2025  14:24    <DIR>          python practice
18-06-2025  10:29            13,939 whie loop.ipynb
              21 File(s)        620,490 bytes
               3 Dir(s)  110,672,732,160 bytes free
hello

In [2]:
import PyPDF2
from PyPDF2 import PdfReader
f="C:\\Users\\sanam\\OneDrive\\Desktop\\The-Happy-Prince-by-Oscar-Wilde.pdf"
print(f)

data=PdfReader(f)
print(data)
text=""
for page in data.pages:
    text+=page.extract_text()
text

C:\Users\sanam\OneDrive\Desktop\The-Happy-Prince-by-Oscar-Wilde.pdf
<PyPDF2._reader.PdfReader object at 0x000002055F7FB620>

'The Happy Prince by Oscar Wilde  \n \nHIGH above the city, on a tall column, stood the statue of the Happ y Prince. \nHe was gilded all over with thin leaves of fine gold, for eyes he ha d two \nbright sapphires, and a large red ruby glowed on his sword- hilt. \nHe was very much admired indeed. “He is as beautiful as a weathercock ,” \nremarked one of the Town Councillors who wished to gain a rep utation for \nhaving artistic tastes; “only not quite so useful,” he added, fear ing lest \npeople should think him unpractical, which he really was not.  \n“Why can’t you be like the Happy Prince?” asked a sensible mother of her \nlittle boy who was crying for the moon. “The Happy Prince never d reams of \ncrying for anything.” \n“I am glad there is someone in the world who is quite happy,” muttered a \ndisappointed man as he gazed at the wonderful statue. \n“He looks just like an angel,” said the Orphans as they came out of the \ncathedral in their bright scarlet cloaks and their clean white pinafores. \n“How do you know?” said the Mathematical Master, “you have never seen \none.” \n“Ah! but we have, in our dreams,” answered the children; and t he \nMathematical Master frowned and looked very severe, for he did not  approve \nof children dreaming. \nOne night there flew over the city a little Swallow. His friends had gone away \nto Egypt six weeks before, but he had stayed behind, for he was in  love with \nthe most beautiful Reed. He had met her early in the spring as he was flying \ndown the river after a big yellow moth, and had been so attra cted by her \nslender waist that he had stopped to talk to her.  \n“Shall I love you?” said the Swallow, who liked to come to t he point at once, \nand the Reed made him a low bow. So he flew round and rou nd her, \ntouching the water with his wings, and making silver ripples. Th is was his \ncourtship, and it lasted all through the summer. \n“It is a ridiculous attachment,” twittered the other Swallow s; “she has no \nmoney, and far too many relations;” and indeed the river was q uite full of \nReeds. Then, when the autumn came they all flew away. \nAfter they had gone he felt lonely, and began to tire of his lad y-love. “She \nhas no conversation,” he said, “and I am afraid that she is a  coquette, for \nshe is always flirting with the wind.” And certainly, whenever th e wind blew, \nthe Reed made the most graceful curtseys. “I admit that she is domesti c,” he continued, “but I love travelling, and my wife, consequently, shou ld love \ntravelling also.” \n“Will you come away with me?” he said finally to her; but the R eed shook \nher head, she was so attached to her home. \n“You have been trifling with me,” he cried. “I am off to the Pyramids. Good-\nbye!” and he flew away. \nAll day long he flew, and at night-time he arrived at the city. “Where shall I \nput up?”  he said; “I hope the town has made preparations.” \nThen he saw the statue on the tall column. \n“I will put up there,” he cried; “it is a fine position, wi th plenty of fresh air.” \nSo he alighted just between the feet of the Happy Prince. \n“I have a golden bedroom,” he said softly to himself as he looked  round, and \nhe prepared to go to sleep; but just as he was putting his head u nder his \nwing a large drop of water fell on him. “What a curious thi ng!” he cried; \n“there is not a single cloud in the sky, the stars are quite clear a nd bright, \nand yet it is raining. The climate in the north of Europe is really dreadful. \nThe Reed used to like the rain, but that was merely her selfishness.”  \nThen another drop fell. \n“What is the use of a statue if it cannot keep the rain off?” h e said; “I must \nlook for  a good chimney-pot,” and he determined to fly away. \nBut before he had opened his wings, a third drop fell, and h e looked up, and \nsaw— Ah! what did he see? The eyes of the Happy Prince were filled wit h \ntears, and tears were running down his golden cheeks. His face was so \nbeautiful in the moonlight that the little Swallow was fi lled with pity. \n“Who are you?” he said. \n“I am the Happy Prince.” \n“Why are you weeping then?” asked the Swallow; “you have quite \ndrenched me.” \n “When I was alive and had a human heart,” answered the statue,  “I did not \nknow what tears were, for I lived in the Palace of Sans-Souci , where sorrow \nis not allowed to enter. In the daytime I played with my compa nions in the \ngarden, and in the evening I led the dance in the Great Hall. R ound the \ngarden ran a very lofty wall, but I never cared to ask what lay beyond it, \neverything about me was so beautiful. My courtiers called me the Hap py \nPrince, and happy indeed I was, if pleasure be happiness. So I l ived, and so I \ndied. And now that I am dead they have set me up here so high th at I can see all the ugliness and all the misery of my city, and though my hea rt is \nmade of lead yet I cannot choose but weep.” \n \n“What! Is he not solid gold?” said the Swallow to  himself. H e was too polite \nto make any personal remarks out loud. \n“Far away,” continued the statue in a low musical voice, “far away in a little \nstreet there is a poor house. One of the windows is open, and th rough it I \ncan see a woman seated at a table. Her face is thin and worn, an d she has \ncoarse, red hands, all pricked by the needle, for she is a seamstress. S he is \nembroidering passion-flowers on a satin gown for the loveliest of  the Queen’s \nmaids -of-honour to wear at the next Cou rt-ball. In a bed in the corner of the \nroom her little boy is lying ill. He has a fever, and is asking f or oranges. His \nmother has nothing to give him but river water, so he is crying. S wallow, \nSwallow, little Swallow, will you not bring her the ruby out of my sword-hilt? \nMy feet are fastened to this pedestal and I cannot move.” \n “I am waited for in Egypt,” said the Swallow. “My friends are flying up and \ndown the Nile, and talking to the large lotus-flowers. Soon they will go to \nsleep in the tomb of the great King. The King is there himself in  his painted \ncoffin. He is wrapped in yellow linen, and embalmed with spices.  Round his \nneck is a chain of pale green jade, and his hands are like wither ed leaves.” \n “Swallow, Swallow, little Swallow,” said the Prince, “w ill you not stay with \nme for one night, and be my messenger? The boy is so thirsty, and the \nmother so sad.” \n“I don’t think I like boys,” answered the Swallow. “Last sum mer, when I was \nstaying on the river, there were two rude boys, the miller’s sons, wh o were \nalways throwing stones at me. They never hit me, of course; we swallo ws fly \nfar too well for that, and besides, I come of a family famo us for its agility; \nbut still, it was a mark of disrespect.” \nBut the Happy Prince looked so sad that the little Swallow w as sorry. “It is \nvery cold here,” he said; “but I will stay with you for one nigh t, and be your \nmessenger.” \n“Thank you, little Swallow,” said the Prince. \nSo the Swallow picked out the great ruby from the Prince’s swor d, and flew \naway with it in his beak over the roofs of the town. \nHe passed by the cathedral tower, where the white marble angels were \nsculptured. He passed by the palace and heard the sound of dancing.  \nA beautiful girl came out on the balcony with her lover. “How  wonderful the \nstars are,” he said to her, “and how wonderful is the power of  love!”   \n“I hope my dress will be ready in time for the State-ball,” sh e answered; \n“I have ordered passion-flowers to be embroidered on it; but the \nseamstresses are so lazy.” \nHe passed over the river, and saw the lanterns hanging to the masts o f the \nships. He passed over the Ghetto, and saw the old Jews bargaining w ith \neach other, and weighing out money in copper scales. At last he came to the \npoor house and looked in. The boy was tossing feverishly on his b ed, and the \nmother had fallen asleep, she was so tired. In he hopped, and l aid the great \nruby on the table beside the woman’s thimble. Then he flew gently round the \nbed, fanning the boy’s forehead with his wings. “How cool I feel !” said the \nboy, “I must be getting better;” and he sank into a delicious slu mber.  \nThen the Swallow flew back to the Happy Prince, and told hi m what he had \ndone. “It is curious,” he remarked, “but I feel quite warm no w, although it is \nso cold.” \n“That is because you have done a good action,” said the Prince. An d the little \nSwallow began to think, and then he fell asleep. Thinking al ways made him \nsleepy. \n \n \n '

In [3]:
print(PyPDF2.__version__)

3.0.1

In [4]:
print(text)

The Happy Prince by Oscar Wilde

HIGH above the city, on a tall column, stood the statue of the Happ y Prince.
He was gilded all over with thin leaves of fine gold, for eyes he ha d two
bright sapphires, and a large red ruby glowed on his sword- hilt.
He was very much admired indeed. “He is as beautiful as a weathercock ,”
remarked one of the Town Councillors who wished to gain a rep utation for
having artistic tastes; “only not quite so useful,” he added, fear ing lest
people should think him unpractical, which he really was not.
“Why can’t you be like the Happy Prince?” asked a sensible mother of her
little boy who was crying for the moon. “The Happy Prince never d reams of
crying for anything.”
“I am glad there is someone in the world who is quite happy,” muttered a
disappointed man as he gazed at the wonderful statue.
“He looks just like an angel,” said the Orphans as they came out of the
cathedral in their bright scarlet cloaks and their clean white pinafores.
“How do you know?” said the Mathematical Master, “you have never seen
one.”
“Ah! but we have, in our dreams,” answered the children; and t he
Mathematical Master frowned and looked very severe, for he did not  approve
of children dreaming.
One night there flew over the city a little Swallow. His friends had gone away
to Egypt six weeks before, but he had stayed behind, for he was in  love with
the most beautiful Reed. He had met her early in the spring as he was flying
down the river after a big yellow moth, and had been so attra cted by her
slender waist that he had stopped to talk to her.
“Shall I love you?” said the Swallow, who liked to come to t he point at once,
and the Reed made him a low bow. So he flew round and rou nd her,
touching the water with his wings, and making silver ripples. Th is was his
courtship, and it lasted all through the summer.
“It is a ridiculous attachment,” twittered the other Swallow s; “she has no
money, and far too many relations;” and indeed the river was q uite full of
Reeds. Then, when the autumn came they all flew away.
After they had gone he felt lonely, and began to tire of his lad y-love. “She
has no conversation,” he said, “and I am afraid that she is a  coquette, for
she is always flirting with the wind.” And certainly, whenever th e wind blew,
the Reed made the most graceful curtseys. “I admit that she is domesti c,” he continued, “but I love travelling, and my wife, consequently, shou ld love
travelling also.”
“Will you come away with me?” he said finally to her; but the R eed shook
her head, she was so attached to her home.
“You have been trifling with me,” he cried. “I am off to the Pyramids. Good-
bye!” and he flew away.
All day long he flew, and at night-time he arrived at the city. “Where shall I
put up?”  he said; “I hope the town has made preparations.”
Then he saw the statue on the tall column.
“I will put up there,” he cried; “it is a fine position, wi th plenty of fresh air.”
So he alighted just between the feet of the Happy Prince.
“I have a golden bedroom,” he said softly to himself as he looked  round, and
he prepared to go to sleep; but just as he was putting his head u nder his
wing a large drop of water fell on him. “What a curious thi ng!” he cried;
“there is not a single cloud in the sky, the stars are quite clear a nd bright,
and yet it is raining. The climate in the north of Europe is really dreadful.
The Reed used to like the rain, but that was merely her selfishness.”
Then another drop fell.
“What is the use of a statue if it cannot keep the rain off?” h e said; “I must
look for  a good chimney-pot,” and he determined to fly away.
But before he had opened his wings, a third drop fell, and h e looked up, and
saw— Ah! what did he see? The eyes of the Happy Prince were filled wit h
tears, and tears were running down his golden cheeks. His face was so
beautiful in the moonlight that the little Swallow was fi lled with pity.
“Who are you?” he said.
“I am the Happy Prince.”
“Why are you weeping then?” asked the Swallow; “you have quite
drenched me.”
 “When I was alive and had a human heart,” answered the statue,  “I did not
know what tears were, for I lived in the Palace of Sans-Souci , where sorrow
is not allowed to enter. In the daytime I played with my compa nions in the
garden, and in the evening I led the dance in the Great Hall. R ound the
garden ran a very lofty wall, but I never cared to ask what lay beyond it,
everything about me was so beautiful. My courtiers called me the Hap py
Prince, and happy indeed I was, if pleasure be happiness. So I l ived, and so I
died. And now that I am dead they have set me up here so high th at I can see all the ugliness and all the misery of my city, and though my hea rt is
made of lead yet I cannot choose but weep.”

“What! Is he not solid gold?” said the Swallow to  himself. H e was too polite
to make any personal remarks out loud.
“Far away,” continued the statue in a low musical voice, “far away in a little
street there is a poor house. One of the windows is open, and th rough it I
can see a woman seated at a table. Her face is thin and worn, an d she has
coarse, red hands, all pricked by the needle, for she is a seamstress. S he is
embroidering passion-flowers on a satin gown for the loveliest of  the Queen’s
maids -of-honour to wear at the next Cou rt-ball. In a bed in the corner of the
room her little boy is lying ill. He has a fever, and is asking f or oranges. His
mother has nothing to give him but river water, so he is crying. S wallow,
Swallow, little Swallow, will you not bring her the ruby out of my sword-hilt?
My feet are fastened to this pedestal and I cannot move.”
 “I am waited for in Egypt,” said the Swallow. “My friends are flying up and
down the Nile, and talking to the large lotus-flowers. Soon they will go to
sleep in the tomb of the great King. The King is there himself in  his painted
coffin. He is wrapped in yellow linen, and embalmed with spices.  Round his
neck is a chain of pale green jade, and his hands are like wither ed leaves.”
 “Swallow, Swallow, little Swallow,” said the Prince, “w ill you not stay with
me for one night, and be my messenger? The boy is so thirsty, and the
mother so sad.”
“I don’t think I like boys,” answered the Swallow. “Last sum mer, when I was
staying on the river, there were two rude boys, the miller’s sons, wh o were
always throwing stones at me. They never hit me, of course; we swallo ws fly
far too well for that, and besides, I come of a family famo us for its agility;
but still, it was a mark of disrespect.”
But the Happy Prince looked so sad that the little Swallow w as sorry. “It is
very cold here,” he said; “but I will stay with you for one nigh t, and be your
messenger.”
“Thank you, little Swallow,” said the Prince.
So the Swallow picked out the great ruby from the Prince’s swor d, and flew
away with it in his beak over the roofs of the town.
He passed by the cathedral tower, where the white marble angels were
sculptured. He passed by the palace and heard the sound of dancing.
A beautiful girl came out on the balcony with her lover. “How  wonderful the
stars are,” he said to her, “and how wonderful is the power of  love!”
“I hope my dress will be ready in time for the State-ball,” sh e answered;
“I have ordered passion-flowers to be embroidered on it; but the
seamstresses are so lazy.”
He passed over the river, and saw the lanterns hanging to the masts o f the
ships. He passed over the Ghetto, and saw the old Jews bargaining w ith
each other, and weighing out money in copper scales. At last he came to the
poor house and looked in. The boy was tossing feverishly on his b ed, and the
mother had fallen asleep, she was so tired. In he hopped, and l aid the great
ruby on the table beside the woman’s thimble. Then he flew gently round the
bed, fanning the boy’s forehead with his wings. “How cool I feel !” said the
boy, “I must be getting better;” and he sank into a delicious slu mber.
Then the Swallow flew back to the Happy Prince, and told hi m what he had
done. “It is curious,” he remarked, “but I feel quite warm no w, although it is
so cold.”
“That is because you have done a good action,” said the Prince. An d the little
Swallow began to think, and then he fell asleep. Thinking al ways made him
sleepy.

In [5]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [6]:
import pandas as pd

In [7]:
filename="C:\\Users\\sanam\\OneDrive\\Desktop\\food dataset\\indian_food.csv"
df = pd.read_csv(filename)
df

,name,ingredients,diet,prep_time,cook_time,flavor_profile,course,state,region
0,Balu shahi,"Maida flour, yogurt, oil, sugar",vegetarian,45,25,sweet,dessert,West Bengal,East
1,Boondi,"Gram flour, ghee, sugar",vegetarian,80,30,sweet,dessert,Rajasthan,West
2,Gajar ka halwa,"Carrots, milk, sugar, ghee, cashews, raisins",vegetarian,15,60,sweet,dessert,Punjab,North
3,Ghevar,"Flour, ghee, kewra, milk, clarified butter, su...",vegetarian,15,30,sweet,dessert,Rajasthan,West
4,Gulab jamun,"Milk powder, plain flour, baking powder, ghee,...",vegetarian,15,40,sweet,dessert,West Bengal,East
...,...,...,...,...,...,...,...,...,...
250,Til Pitha,"Glutinous rice, black sesame seeds, gur",vegetarian,5,30,sweet,dessert,Assam,North East
251,Bebinca,"Coconut milk, egg yolks, clarified butter, all...",vegetarian,20,60,sweet,dessert,Goa,West
252,Shufta,"Cottage cheese, dry dates, dried rose petals, ...",vegetarian,-1,-1,sweet,dessert,Jammu & Kashmir,North
253,Mawa Bati,"Milk powder, dry fruits, arrowroot powder, all...",vegetarian,20,45,sweet,dessert,Madhya Pradesh,Central
254,Pinaca,"Brown rice, fennel seeds, grated coconut, blac...",vegetarian,-1,-1,sweet,dessert,Goa,West

In [8]:

filepath="C:\\Users\\sanam\\OneDrive\\Desktop\\exel data\\Employee Sample Data.xlsx"
df= pd.read_excel(filepath)
df

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,E03094,Wesley Young,Sr. Analyst,Marketing,Speciality Products,Male,Caucasian,33,2016-09-18,98427,0.00,United States,Columbus,NaT
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44,2010-05-31,47387,0.00,China,Chengdu,2018-01-08
997,E04398,Oliver Yang,Director,Marketing,Speciality Products,Male,Asian,31,2019-06-10,176710,0.15,United States,Miami,NaT
998,E02521,Lily Nguyen,Sr. Analyst,Finance,Speciality Products,Female,Asian,33,2012-01-28,95960,0.00,China,Chengdu,NaT
999,E03545,Sofia Cheng,Vice President,Accounting,Corporate,Female,Asian,63,2020-07-26,216195,0.31,United States,Miami,NaT

In [9]:
pip install lxml

Requirement already satisfied: lxml in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (6.0.0)
Note: you may need to restart the kernel to use updated packages.

In [10]:
filepath="C:\\Users\\sanam\\OneDrive\\Desktop\\exel data\\Employee Sample Data.xlsx"
df= pd.read_excel(filepath)
df

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,E03094,Wesley Young,Sr. Analyst,Marketing,Speciality Products,Male,Caucasian,33,2016-09-18,98427,0.00,United States,Columbus,NaT
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44,2010-05-31,47387,0.00,China,Chengdu,2018-01-08
997,E04398,Oliver Yang,Director,Marketing,Speciality Products,Male,Asian,31,2019-06-10,176710,0.15,United States,Miami,NaT
998,E02521,Lily Nguyen,Sr. Analyst,Finance,Speciality Products,Female,Asian,33,2012-01-28,95960,0.00,China,Chengdu,NaT
999,E03545,Sofia Cheng,Vice President,Accounting,Corporate,Female,Asian,63,2020-07-26,216195,0.31,United States,Miami,NaT

In [11]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\sanam\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
filepath="C:\\Users\\sanam\\OneDrive\\Desktop\\exel data\\Employee Sample Data.xlsx"
df= pd.read_excel(filepath)
df

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,E03094,Wesley Young,Sr. Analyst,Marketing,Speciality Products,Male,Caucasian,33,2016-09-18,98427,0.00,United States,Columbus,NaT
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44,2010-05-31,47387,0.00,China,Chengdu,2018-01-08
997,E04398,Oliver Yang,Director,Marketing,Speciality Products,Male,Asian,31,2019-06-10,176710,0.15,United States,Miami,NaT
998,E02521,Lily Nguyen,Sr. Analyst,Finance,Speciality Products,Female,Asian,33,2012-01-28,95960,0.00,China,Chengdu,NaT
999,E03545,Sofia Cheng,Vice President,Accounting,Corporate,Female,Asian,63,2020-07-26,216195,0.31,United States,Miami,NaT

In [13]:
import xml.etree.ElementTree as ET

In [14]:
tree = ET.parse('D:\\iso redhat\\large-dataset.xml')
root=tree.getroot()
print(root.tag)
print(root.attrib)

employees
{}

In [15]:
for child in root:
    #print(child.tag,child.attrib)

_IncompleteInputError: incomplete input (2797560743.py, line 2)

In [ ]:
# Access the first child of the root, then its second child
specific_element=root[0][0]
print(specific_element.tag)
print(specific_element.text)

In [ ]:
pip install beautifulsoup4

In [ ]:
pip install lxml

In [16]:
with open('D:\\iso redhat\\large-dataset.xml','r') as f:
    data= f.read()
    print(data)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [17]:
with open('D:\\iso redhat\\sample1.xml','r') as s:
    seq= s.read()
    print(seq)

<root>
  <person>
    <name>John Doe</name>
    <age>30</age>
    <email>john.doe@example.com</email>
  </person>
  <person>
    <name>Jane Smith</name>
    <age>25</age>
    <email>jane.smith@example.com</email>
  </person>
  <book>
    <title>The Adventure Begins</title>
    <author>Robert Johnson</author>
    <year>2022</year>
  </book>
</root>